app/views.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, abort, Markup
from pymetasploit3.msfrpc import MsfRpcClient, MsfAuthError
from flask_login import login_user, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from models import db, User, Report, Setting
from utils import error_resp, success_resp
from app import env, create_app
import re
import os
import markdown
import requests

index = Blueprint('index', __name__, static_folder='static', template_folder='templates')

app = create_app()

@index.route('/', methods=['GET'])
def home():
    if request.method == 'GET':
        return render_template('home.html')


@index.route('/scans')
def show_scans():
    login = current_user.is_authenticated
    if login:
        return render_template('general_scans.html', login=login)
    else:
        return error_resp('Must be logged in to see scans')

@index.route('/exploits')
def show_exploits():
    login = current_user.is_authenticated
    if login:
        return render_template('general_exploits.html', login=login)
    else:
        return error_resp('Must be logged in to see scans')

@index.route('/login')
def login():
    login = current_user.is_authenticated
    if login:
        return redirect(url_for('index.home'))
    return render_template('login.html',
                           login=login,
                           name=current_user.username if login else None,
                           )

@index.route('/auth', methods=['GET', 'POST', 'PATCH', 'DELETE'])
def auth():
    # For getting user info
    if request.method == 'GET':
        if current_user.is_authenticated:
            return {'Username': current_user.username}
        return jsonify({'username': None})

    # For logging in
    elif request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        remember = True if request.form.get('remember') else False
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user, remember=remember)
            return redirect(url_for('index.home'))
        return redirect(url_for('index.login'))

    # For changing password
    elif request.method == 'PATCH':
        if current_user.is_authenticated:
            old_password = request.form.get('old_password')
            password = request.form.get('new_password')
            if check_password_hash(current_user.password, old_password):
                user = User.query.filter_by(username=current_user.username).first()
                user.password = generate_password_hash(password, method='pbkdf2:sha256')
                db.session.add(user)
                db.session.commit()
                return success_resp('Password updated')
            return error_resp('Current password is incorrect')
        return error_resp('Unauthenticated')

    # For logging out
    elif request.method == 'DELETE':
        logout_user()
        return success_resp('Logged out')


@index.route('/logout')
def logout():
    # Allow the user to log out
    logout_user()
    return redirect(url_for('index.home'))

@index.route("/register", methods=['GET', 'POST'])
def register():
    """Renders a webpage that allows user to register new users"""
    login = current_user.is_authenticated
    if not login:
        return abort(401)
    if request.method == "GET":
        return render_template("register.html", login=login)
    elif request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        passwordSecond = request.form.get("password2")
        if not (username and password and passwordSecond):
            return render_template("register.html", registerError = "Please complete all the fields", login=login)
        if password != passwordSecond:
            return render_template("register.html", registerError = "Passwords do not match", login=login)
        if len(password) < 8 or not re.search("[a-zA-Z]", password) or not re.search("[0-9]", password):
            registerError = "<div class='text-start'>Password do not meet the requirements:\
            \n<ul><li>Password needs to have at least 8 characters</li>\
            \n<li>Password needs to contain at least one letter</li>\
            \n<li>Password needs to contain at least one number</li></ul></div>";
            return render_template("register.html", registerError = registerError, login=login)
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template("register.html", registerError = "This username has already been taken, please try a different username", login=login)
        newUser = User(
            username=username,
            password=generate_password_hash(password, "pbkdf2:sha256")
            )
        # with app.app_context():
        db.session.add(newUser)
        db.session.commit()
        return redirect(url_for('index.home')) 

@index.route("/users", methods=["GET"])
def users():
    """Renders a webpage with a list of users"""
    login = current_user.is_authenticated
    if not login:
        return abort(401)
    users = User.query.all()
    ret = []
    if users:
        ret = [(user.id, user.username) for user in users]
    return render_template('user_list.html', user_list=ret, login=login)


@index.route("/profile", methods=["GET", "POST"])
def profile():
    """Renders a webpage that allows users to update their password"""
    login = current_user.is_authenticated
    if not login:
        return abort(401)
    if request.method == "GET":
        return render_template("profile.html", user=current_user.username, login=login)
    else:
        password = request.form.get("new_password")
        old_password = request.form.get("old_password")
        if not (password and old_password):
            return render_template("profile.html", registerError = "Please complete all the fields", login=login, user=current_user.username)
        if len(password) < 8 or not re.search("[a-zA-Z]", password) or not re.search("[0-9]", password):
            registerError = "<div class='text-start'>Password do not meet the requirements:\
            \n<ul><li>Password needs to have at least 8 characters</li>\
            \n<li>Password needs to contain at least one letter</li>\
            \n<li>Password needs to contain at least one number</li></ul></div>";
            return render_template("profile.html", registerError = registerError, login=login, user=current_user.username)
        if check_password_hash(current_user.password, old_password):
            user = User.query.filter_by(username=current_user.username).first()
            user.password = generate_password_hash(password, method='pbkdf2:sha256')
            db.session.add(user)
            db.session.commit()
            return render_template("profile.html", success = True, login=login, user=current_user.username)
        return render_template("profile.html", registerError = "Current password is incorrect", login=login, user=current_user.username)


@index.route('/reports/<id>')
def show_report(id):
    """
    Renders a webpage that displays the report with the specified id.
    args:
        id: The id field of the report in the database
    """
    login = current_user.is_authenticated
    if not login:
        return abort(401)
    report = Report.query.filter_by(id=id).first()
    if not report:
        return abort(404)
    report_markdown = report.content
    report_html = markdown.markdown(report_markdown, extensions=['tables', "sane_lists"])
    report_html = report_html.replace("<table>", '<table class="table">')
    report_html = Markup(report_html)
    return render_template('report.html', report=report_html, login=login)


@index.route("/reports")
def list_reports():
    """Renders a webpage with a list of reports"""
    login = current_user.is_authenticated
    if not login:
        return abort(401)
    reports = Report.query.all()
    ret = []
    if reports:
        ret = [(report.id, report.ip, report.time.strftime("%Y-%m-%d"), report.time.strftime("%H:%M:%S")) for report in reports]
    message = ""
    if len(ret) == 0:
        message = "You have not done any scan"
    return render_template('report_list.html', report_names=ret, message=message, login=login)

@index.route("/shells")
def list_shells():
    """Renders a webpage with a list of shells"""
    login = current_user.is_authenticated
    if not login:
        return abort(401)
    try:
        msf_manager = MsfRpcClient(env.msf_password, ip=env.msf_ip, port=env.msf_port)
        shells = msf_manager.sessions.list
    except (MsfAuthError, requests.exceptions.ConnectionError):
        return error_resp("MsfRPC server is offline.")
    ret = []
    for shell_id, shell in shells.items():
        ret.append((shell_id,
                   shell['target_host'],
                   shell['session_port'],
                   shell['type'],
                   shell['arch'],
                   shell['desc'],
                   shell['via_exploit'],
                   shell['via_payload']))
    message = ""
    if len(ret) == 0:
        message = "You have not done any scan"
    return render_template('shell_list.html', shell_index=ret, message=message, login=login)

@index.route('/shells/<id>', methods=['GET', 'POST'])
def shell_interface(id):
    """Renders a webpage where users can interact with the shell with the specified id."""
    login = current_user.is_authenticated

    if not login:
        return error_resp('Must be logged in to see scans')

    try:
        msf_manager = MsfRpcClient(env.msf_password, ip=env.msf_ip, port=env.msf_port)
        shell = msf_manager.sessions.session(id)
    except (MsfAuthError, requests.exceptions.ConnectionError):
        return error_resp("MsfRPC server is offline.")

app/templates/front_page.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset = "UTF-8">
        <title>CTRL-X</title>
    </head>
    <body>
        <h1>Welcome to CTRL-X</h1>
        <a href={{url_for("send_data")}} >
            <button>Request Data</button>
        </a>
    </body>
</html>

app/templates/general_scans.html
{% extends "layout.html" %}

{% block title %}
CTRL-X
{% endblock %}

{% block imports %}
<script type="text/javascript" src="{{ url_for('static', filename='scan.js') }}"></script>
{% endblock %}
{% block body %}
    <div class="container w-75">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">IP/Report Links</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody id="ip-container">
            </tbody>
        </table>
    </div>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock %}
{% block imports %}
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{{url_for('static', filename='form.js')}}"></script>
<script src="{{url_for('static', filename='settings.js')}}"></script>
<script src="{{url_for('static', filename='make_chart.js')}}"></script>
{% endblock %}
{% block header %}
{% if current_user.is_authenticated %}
Welcome to CTRL-X, {{ current_user.username }}!
{% else %}
Welcome to CTRL-X!
{% endif %}
{% endblock %}
{% block body %}
<!-- <a href="{{url_for('index.show_scans')}}" >
    <button>Request Data</button>
    </a> -->
<div class="container text-center">
    <br>
    <h4>We're so glad you're here to help us in our mission to help make cybersecurity more accessible to everyone!</h4>
</div>
<div class="container">
    <hr class="hr-blurry" />
</div>
{% if current_user.is_authenticated %}
<div class="d-flex flex-row justify-content-center">
    <h3>Request New Job</h3>
</div>
<div class="d-flex flex-row justify-content-center">
    <div class="card text-center homepage-card w-25">
        <div class="card-body">
            <p class="card-text">Request new jobs by inputting the target IP and optionally port(s).</p><br>
            <form id="ip-form">
                <div class="row">
                    <div class="col">
                        <label for="ip_block">Target IP Address:</label>
                        <input type="text" class="form-control text-center" id="ip_block" name="ip_block"><br>
                    </div>
                    <div class="col">
                        <label for="ports">Target Port(s) (optional):</label>
                        <input type="text" class="form-control text-center" id="ports" name="ports"><br> 
                    </div>
                </div>
                <input class="small-mt btn btn-primary" type="submit" value="Submit">
                <p class="card-text" id="response" name="response"></p>
            </form>
        </div>
    </div>
</div>
<div class="container">
    <hr class="hr-blurry" />
</div>
<div class="d-flex flex-row justify-content-center">
    <h3>View running and completed jobs</h3>
</div>
<div class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-row w-25 steps justify-content-end">
        <h3></h3>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card text-center homepage-card" >
            <div class="card-body">
                <h5 class="card-title">Scans</h5>
                <p class="card-text">View running and completed scan jobs.</p>
                <a href="{{url_for('index.show_scans')}}" class="btn btn-primary">Go to Data</a>
            </div>
        </div>
        <div class="card text-center homepage-card" >
            <div class="card-body">
                <h5 class="card-title">Exploits</h5>
                <p class="card-text">View running and completed exploit jobs requested.</p>
                <a href="{{url_for('index.show_exploits')}}" class="btn btn-primary">Go to Data</a>
            </div>
        </div>
        <div class="card text-center homepage-card" >
            <div class="card-body">
                <h5 class="card-title">Shells</h5>
                <p class="card-text">View active shells.</p>
                <a href="{{url_for('index.list_shells')}}" class="btn btn-primary">Go to Data</a>
            </div>
        </div>
        <div class="card text-center homepage-card">
            <div class="card-body">
                <h5 class="card-title">Reports</h5>
                <p class="card-text">View reports of past scans.</p>
                <a href="{{url_for('index.list_reports')}}" class="btn btn-primary">Go to Reports</a>
            </div>
        </div>
    </div>
    <div class="d-flex flex-row w-25 instruct justify-content-start">
        <h3></h3>
    </div>
</div>
<div class="container" style="margin-top:2em">
    <hr class="hr-blurry" />
</div>
<div class="d-flex flex-row justify-content-center">
    <h3>Settings</h3>
</div>
<div class="d-flex justify-content-center">
    <div class="card text-center homepage-card">
        <div class="card-body">
            <h5 class="card-title">Manage users</h5>
            <p class="card-text">View and create users.</p>
            <a href="{{url_for('index.users')}}" class="btn btn-primary">View other users</a>
            <br>
            <br>
            <a href="{{url_for('index.register')}}" class="btn btn-primary">Register new users</a>
        </div>
    </div>
    <div class="card text-center homepage-card">
        <div class="card-body">
            <h5 class="card-title">Settings</h5>
            <p class="card-text">Modify Nmap scan options</p>
            <form id="command-form">
                <label for="command">New Nmap Args:</label><br>
                <input type="text" class="form-control" id="command" name="command">
                <label for="command" style="margin-top:10%">DNS:</label><br>
                <input type="text" class="form-control" id="dns" name="dns">
                <input class="small-mt btn btn-primary" type="submit" value="Submit">
                <p class="card-text" id="response_settings" name="response_settings"></p>
            </form>
            <button id="def" name="default" type="button" class="btn btn-primary">Default</button>
        </div>
    </div>
</div>
<div class="container" style="margin-top:2em">
    <hr class="hr-blurry" />
</div>
<div class="d-flex flex-row justify-content-center">
    <h3>Statistics</h3>
</div>
<div class="row">
    <div class="col-1"></div>
    <div class="col-5 chart">
        <canvas id="scan_chart"></canvas>
    </div>
    <div class="col-5 chart">
        <canvas id="ip_chart"></canvas>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset = "UTF-8">
        <title>CTRL-X</title>
    </head>
    <body>
        <h1>Welcome to CTRL-X</h1>
        <a href="{{url_for('index.show_scans')}}" >
            <button>Request Data</button>
        </a>
    </body>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>CTRL-X | {% block title %}{% endblock %}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
        crossorigin="anonymous">
    <link href="{{ url_for('static', filename='style.css') }}" 
    rel="stylesheet" 
    >

    {% block imports %}
    {% endblock %}
</head>
<body data-bs-theme="dark">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('index.home')}}">CTRL-X</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('index.home')}}">Home</a>
              </li>
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('index.profile')}}">Profile</a>
              </li>    
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('index.logout')}}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('index.login')}}">Login</a>
              </li>
              {% endif %}      
            </ul>
          </div>
        </div>
    </nav>
  <div class="d-flex justify-content-center">
    <h1 style="padding-top:2em">
      {% block header %}{% endblock %}
    </h1>
  </div>
  <div class="d-flex flex-column justify-content-evenly mb-4">
    {% block body %}{% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
        crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" 
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" 
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" 
      crossorigin="anonymous"></script>
</body>
</html>

app/templates/profile.html
{% extends "layout.html" %}

{% block title %}Profile{% endblock %}

{% block imports %}
<link href="{{ url_for('static', filename='register.css') }}" 
rel="stylesheet" 
>
{% endblock %}

{% block body %}    
  <div class="container-xxl">
    <h3 class="text-center">Username: {{user}}</h3>
    <div class="container">
      <form action="{{url_for('index.profile')}}" method="POST" class="needs-validation" id="registerForm" novalidate>
          <div class="row mb-3">
              <div class="col-0 col-md-4"></div>
              <div class="col-md-4">
                <div class="form-floating">
                  <input type="password" class="form-control registerInput" id="oldPassword" name="old_password" placeholder="Old Password" required>
                  <label for="oldPassword">Old Password</label>
                </div>
              </div>
          </div>
          <div class="row mb-3">
          <div class="col-0 col-md-4"></div>
          <div class="col-md-4">
            <div class="form-floating">
              <input type="password" class="form-control registerInput" id="regPassword" name="new_password" 
              placeholder="Password" pattern="(?=.*\d)(?=.*[a-zA-Z]).{8,}" required>
              <label for="regPassword">Password</label>
              <div class="invalid-feedback feedback">
                <p id="length">At least 8 characters</p>
                <p id="letter">Contain at least one letter</p>
                <p id="number">Contain at least one number</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-0 col-md-4">
          </div>
          <div class="col-md-4">
            <button class="btn btn-outline-success w-100" type="submit">Update password</button>
          </div>
        </div>
        {% if registerError %}
        <div class="row mb-3">
          <div class="col-0 col-md-4">
          </div>
          <div class="col-md-4">
            <div class='text-center alert alert-danger'>
              {{registerError}}
            </div>
          </div>
        </div>
        {% endif %}
        {% if success %}
        <div class="row mb-3">
          <div class="col-0 col-md-4">
          </div>
          <div class="col-md-4">
            <div class='text-center alert alert-success'>
              Password updated
            </div>
          </div>
        </div>
        {% endif %}
      </form>
    </div>
  </div>
  <script type="text/javascript" src="{{ url_for('static', filename='registerValidate.js') }}"></script>
{% endblock %}

app/templates/register.html
{% extends "layout.html" %}

{% block title %}Login{% endblock %}

{% block imports %}
<link href="{{ url_for('static', filename='register.css') }}" 
rel="stylesheet" 
>
{% endblock %}

{% block body %}    
    <div class="container-xxl">
      <h2 class="text-center">Register a new account </h2>
      <div class="container">
        <form action="{{url_for('index.register')}}" method="POST" class="needs-validation" id="registerForm" novalidate>
          <div class="row mb-3">
            <div class="col-0 col-md-4"></div>
            <div class="col-md-4">
              <div class="form-floating">
                <input type="text" class="form-control registerInput" id="regUsername" name="username" placeholder="Username" autocomplete="on" required>
                <label for="regUsername">Username</label>
                <div class="invalid-feedback">
                  Please enter a username.
                </div>
              </div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-0 col-md-4"></div>
            <div class="col-md-4">
              <div class="form-floating">
                <input type="password" class="form-control registerInput" id="regPassword" name="password" 
                placeholder="Password" pattern="(?=.*\d)(?=.*[a-zA-Z]).{8,}" required>
                <label for="regPassword">Password</label>
                <div class="invalid-feedback feedback">
                  <p id="length">At least 8 characters</p>
                  <p id="letter">Contain at least one letter</p>
                  <p id="number">Contain at least one number</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-0 col-md-4"></div>
            <div class="col-md-4">
              <div class="form-floating">
                <input type="password" class="form-control registerInput" id="regPassword2" name="password2" placeholder="Repeat Password" required>
                <label for="regPassword2">Repeat Password</label>
                <div class="invalid-feedback">
                  Passwords do not match
                </div>
              </div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-0 col-md-4">
            </div>
            <div class="col-md-4">
              <button class="btn btn-outline-success w-100" type="submit">Register</button>
            </div>
          </div>
          {% if registerError %}
          <div class="row mb-3">
            <div class="col-0 col-md-4">
            </div>
            <div class="col-md-4">
              <div class='text-center alert alert-danger'>
                {{registerError}}
              </div>
            </div>
          </div>
          {% endif %}
        </form>
      </div>
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='registerValidate.js') }}"></script>
{% endblock %}

app/templates/report.html
{% extends "layout.html" %}

{% block title %}
Report
{% endblock %}

{% block body %}
<div class="container">
    {{report}}
</div>
{% endblock %}

{% block imports %}

{% endblock %}

app/templates/report_list.html
{% extends "layout.html" %}

{% block title %}
Report
{% endblock %}

{% block body %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
              <th scope="col">Network scanned</th>
              <th scope="col">Date</th>
              <th scope="col">Time</th>
            </tr>
          </thead>
          <tbody>
            {% for name in report_names%}
                <tr>
                    <td>
                        <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="/reports/{{name[0]}}">
                            {{name[1]}}
                        </a>
                    </td>
                    <td>{{name[2]}}</td>
                    <td>{{name[3]}}</td>
                </tr>
            {% endfor %}
          </tbody>
    </table>
</div>
{% endblock %}

{% block imports %}

{% endblock %}

app/templates/scan.html
{% extends "layout.html" %}

{% block title %}
Scan
{% endblock %}

{% block body %}
<div class="container">
    <h2>Scan result</h2>
    {% for scan in scan_list%}
    <table class="table">
        <tbody>
            {% for field in scan.keys() %}
            {% if field != "scan_data" %}
            <tr>
                <th>
                    {{field}}
                </th>
                <td>
                    {% if field == "scan_result" %}
                    <pre class="width-limit">{{scan[field]}}</pre>
                    {% else %}
                    {{scan[field]}}
                    {% endif %}
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% endfor %}
</div>
{% endblock %}

app/templates/shell.html
<!-- Include Socket.IO -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.3.2/socket.io.min.js"></script>

<!-- Your HTML code -->
<body>
    <input type="text" id="commandInput" placeholder="Enter command...">
    <button onclick="sendCommand()">Execute</button>
    <pre id="output"></pre>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Establish Socket.IO connection
            var socket = io.connect('https://' + document.domain + ':' + location.port);

            function sendCommand() {
                var commandInput = document.getElementById('commandInput').value;
                socket.emit('input_command', commandInput);
            }

            socket.on('output_response', function(data) {
                document.getElementById('output').textContent = data.output;
            });
        });
    </script>
</body>

app/templates/shell_interface.html
{% extends "layout.html" %}

{% block title %}
Shell Interface
{% endblock %}

{% block body %}
<div class="container">
    <h2>Shell Interface</h2>
    <form method="POST">
        <div class="mb-3">
            <label for="command" class="form-label">Execute new command:</label>
            <input type="text" class="form-control" id="command" name="command" required>
        </div>
        <button type="submit" class="btn btn-primary">Execute</button>
    </form>
    <div class="container">
        <hr class="hr-blurry" />
    </div>
    {% if command %}
    <h3 class="mt-4">Command Executed:</h4>
    <p>{{ command }}</p>
    {% endif %}
    {% if output %}
    <h3 class="mt-4">Output:</h4>
    <pre>{{ output }}</pre>
    {% endif %}
</div>
{% endblock %}

app/templates/underground.html
{% extends "layout.html" %}


{% block title %}Underground{% endblock %}

{% block body %}
{% if login %}
    <h1>Logged In</h1>
{% else %}
    {% include "components/login-modal.html" %}
{% endif %}
{% endblock %}

app/templates/user_list.html
{% extends "layout.html" %}

{% block title %}
Users
{% endblock %}

{% block body %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
              <th scope="col">User ID</th>
              <th scope="col">User name</th>
            </tr>
          </thead>
          <tbody>
            {% for name in user_list%}
                <tr>
                    <td>
                        {{name[0]}}
                    </td>
                    <td>{{name[1]}}</td>
                </tr>
            {% endfor %}
          </tbody>
    </table>
</div>
{% endblock %}

{% block imports %}

{% endblock %}